[package]
name = "chlang"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
# backtrace-on-stack-overflow = "0.3.0"
pix-engine = {version = "0.8.0", optional = true }
rand = "0.8.5"

[features]
default = ["gui"]
gui = ["dep:pix-engine"]
